/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Codigo;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.io.StringReader;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.runtime.Symbol;
import javax.swing.JFileChooser;

/**
 *
 * @author user
 */
public class pFinal extends javax.swing.JFrame {

    /**
     * Creates new form pFinal
     */
    public pFinal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_abrir = new javax.swing.JButton();
        Btn_anLex = new javax.swing.JButton();
        Btn_Lim = new javax.swing.JButton();
        Btn_anSin = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAbrir = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtSintactico = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtLexico = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Analizador Lexico/Sintactico");

        Btn_abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Codigo/icons8-abrir-documento-48.png"))); // NOI18N
        Btn_abrir.setText("Abrir Archivo");
        Btn_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_abrirActionPerformed(evt);
            }
        });

        Btn_anLex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Codigo/icons8-letra-pequeña-48.png"))); // NOI18N
        Btn_anLex.setText("Analizar");
        Btn_anLex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_anLexActionPerformed(evt);
            }
        });

        Btn_Lim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Codigo/icons8-borrar-para-siempre-48.png"))); // NOI18N
        Btn_Lim.setText("Limpiar");
        Btn_Lim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_LimActionPerformed(evt);
            }
        });

        Btn_anSin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Codigo/icons8-letra-pequeña-48.png"))); // NOI18N
        Btn_anSin.setText("Analizar");
        Btn_anSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_anSinActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(txtAbrir);

        jScrollPane5.setViewportView(txtSintactico);

        jScrollPane6.setViewportView(txtLexico);

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel3.setText("Codigo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(306, 306, 306))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(433, 50));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel1.setText("Analizador Lexico");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(433, 50));

        jLabel2.setBackground(new java.awt.Color(51, 204, 0));
        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel2.setText("Analizador Sintactico");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(581, 581, 581)
                        .addComponent(Btn_Lim))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btn_anSin)
                                .addGap(66, 66, 66)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Btn_anLex)
                                    .addComponent(Btn_abrir))
                                .addGap(45, 45, 45)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(Btn_abrir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane4)))
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_anLex)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Btn_Lim)
                        .addGap(39, 39, 39)))
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(Btn_anSin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void analizadorLexico() throws IOException{
    int cont=1;
    String expr = (String) txtAbrir.getText();
    Lexer lexer = new Lexer (new StringReader(expr));
    String resultado= "Linea "+ cont+"\t\t SIMBOLO\t\n";
    while(true)
    {
        Tokens token= lexer.yylex();
        if(token==null)
    {
        resultado +="Terminado";
        txtLexico.setText(resultado);
        return;
    }
        switch(token){
            case Linea:
                cont++;
        resultado += "Linea "+ cont +"\n";
        break;
            case Principal:
                resultado += "<Reservada Principal>\t\t"+ lexer.lexeme +"\n";
                break;
            case Clase:
                resultado += "<Reservada Clase>\t\t"+ lexer.lexeme +"\n";
                break;
            case Publico:
                resultado += "<Reservada Publico>\t\t"+ lexer.lexeme +"\n";
                break;
            case Entero:
                resultado += "<Reservada Entero>\t\t"+ lexer.lexeme +"\n";
                break;
            case Caracter:
                resultado += "<Reservada Caracter>\t\t"+ lexer.lexeme +"\n";
                break;
            case Privado:
                resultado += "<Reservada Privado>\t\t"+ lexer.lexeme +"\n";
                break;  
            case Entonces:
                resultado += "<Reservada Entonces>\t\t"+ lexer.lexeme +"\n";
                break;
            case Ademas:
                resultado += "<Reservada Ademas>\t\t"+ lexer.lexeme +"\n";
                break;
            case Para:
                resultado += "<Reservada Para>\t\t"+ lexer.lexeme +"\n";
                break;
            case Mientras:
                resultado += "<Reservada Mientras>\t\t"+ lexer.lexeme +"\n";
                break;
            case AbreParentesis:
                resultado += "<Apertura de Parentesis>\t\t"+ lexer.lexeme +"\n";
                break;
            case CierraParentesis:
                resultado += "<Cierre de Parentesis>\t\t"+ lexer.lexeme +"\n";
                break;
            case Llave_a:
                resultado += "<Apertura de LLave>\t\t"+ lexer.lexeme +"\n";
                break;
            case Llave_c:
                resultado += "<Cierre de LLave>\t\t"+ lexer.lexeme +"\n";
                break;
            case P_Coma:
                resultado += "<Punto y coma>\t\t"+ lexer.lexeme +"\n";
                break;
            case MayorQue:
                resultado += "<Signo Mayor>\t\t"+ lexer.lexeme +"\n";
                break;
            case MenorQue:
                resultado += "<Signo Menor>\t\t"+ lexer.lexeme +"\n";
                break;
            case Igual:
                resultado += "<Signo Igual>\t\t"+ lexer.lexeme +"\n";
                break;
            case Suma:
                resultado += "<Suma >\t\t"+ lexer.lexeme +"\n";
                break;
            case Resta:
                resultado += "<Resta >\t\t"+ lexer.lexeme +"\n";
                break;
            case Multiplicacion:
                resultado += "<Multiplicacion >\t\t"+ lexer.lexeme +"\n";
                break;
            case Division:
                resultado += "<Division >\t\t"+ lexer.lexeme +"\n";
                break;
            case Identificador:
                resultado += "<Identificador>\t\t"+ lexer.lexeme +"\n";
                break;
            case Numero:
                resultado += "<Numero >\t\t"+ lexer.lexeme +"\n";
                break;
                
            case ERROR:
                resultado += "<simbolo no definido>\t\t"+ lexer.lexeme +"\n";
                break;
        }
    }    
}
    private void Btn_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_abrirActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File archivo = new File (chooser.getSelectedFile().getAbsolutePath());
                 
        String ST;        
        try {
            ST = new String(Files.readAllBytes(archivo.toPath()));
            txtAbrir.setText(ST);
        } catch (IOException ex) {
            Logger.getLogger(pFinal.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_Btn_abrirActionPerformed

    private void Btn_LimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_LimActionPerformed
        // TODO add your handling code here:
        txtAbrir.setText("");
        txtLexico.setText("");
        txtSintactico.setText("");
    }//GEN-LAST:event_Btn_LimActionPerformed

    private void Btn_anLexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_anLexActionPerformed
        try {
            // TODO add your handling code here:
            analizadorLexico();
        } catch (IOException ex) {
            Logger.getLogger(pFinal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_anLexActionPerformed

    private void Btn_anSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_anSinActionPerformed
        // TODO add your handling code here:
        String ST= txtAbrir.getText();
        Sintax s= new Sintax(new Codigo.LexerCup(new StringReader(ST)));
        try {
            s.parse();
            txtSintactico.setText("analisis realizado correctamente");
            txtSintactico.setForeground(Color.green);
        } catch (Exception ex) {
            Symbol sym= s.getS();
            txtSintactico.setText("error de sintaxis. linea:"+(sym.right+1)+" Columna"+(sym.left+1)+" texto:\""+sym.value+"\"");
            txtSintactico.setForeground(Color.red);
        }
    }//GEN-LAST:event_Btn_anSinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Lim;
    private javax.swing.JButton Btn_abrir;
    private javax.swing.JButton Btn_anLex;
    private javax.swing.JButton Btn_anSin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextPane txtAbrir;
    private javax.swing.JTextPane txtLexico;
    private javax.swing.JTextPane txtSintactico;
    // End of variables declaration//GEN-END:variables
}
