
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 09 13:08:37 CST 2021
//----------------------------------------------------

package Codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MayorQue = 18;
  public static final int Privado = 8;
  public static final int Clase = 4;
  public static final int Suma = 21;
  public static final int Numero = 26;
  public static final int Entero = 6;
  public static final int ERROR = 27;
  public static final int Mientras = 12;
  public static final int Para = 11;
  public static final int Identificador = 25;
  public static final int Llave_c = 16;
  public static final int Llave_a = 15;
  public static final int P_coma = 17;
  public static final int CierraParentesis = 14;
  public static final int EOF = 0;
  public static final int Division = 24;
  public static final int Entonces = 9;
  public static final int Resta = 22;
  public static final int Linea = 2;
  public static final int Publico = 5;
  public static final int error = 1;
  public static final int Igual = 20;
  public static final int AbreParentesis = 13;
  public static final int Multiplicacion = 23;
  public static final int MenorQue = 19;
  public static final int Caracter = 7;
  public static final int Ademas = 10;
  public static final int Principal = 3;
}

